# Generated by Django 3.1.6 on 2021-05-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redSocial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(default='batman.png', upload_to=''),
        ),
    ]
